//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.1.
// 
#pragma warning disable 1591

namespace METAOPTION.UCR {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="LinkCRServiceSoap", Namespace="http://metaoption.com")]
    public partial class LinkCRService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private UserCredentials userCredentialsValueField;
        
        private System.Threading.SendOrPostCallback GetUCRDetailToLinkOperationCompleted;
        
        private System.Threading.SendOrPostCallback VerifyURLOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public LinkCRService() {
            this.Url = global::METAOPTION.Properties.Settings.Default.HeadStartVMS_UCR_LinkCRService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public UserCredentials UserCredentialsValue {
            get {
                return this.userCredentialsValueField;
            }
            set {
                this.userCredentialsValueField = value;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetUCRDetailToLinkCompletedEventHandler GetUCRDetailToLinkCompleted;
        
        /// <remarks/>
        public event VerifyURLCompletedEventHandler VerifyURLCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("UserCredentialsValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://metaoption.com/GetUCRDetailToLink", RequestNamespace="http://metaoption.com", ResponseNamespace="http://metaoption.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ServiceResponce GetUCRDetailToLink(int crID, string vin, short matchType) {
            object[] results = this.Invoke("GetUCRDetailToLink", new object[] {
                        crID,
                        vin,
                        matchType});
            return ((ServiceResponce)(results[0]));
        }
        
        /// <remarks/>
        public void GetUCRDetailToLinkAsync(int crID, string vin, short matchType) {
            this.GetUCRDetailToLinkAsync(crID, vin, matchType, null);
        }
        
        /// <remarks/>
        public void GetUCRDetailToLinkAsync(int crID, string vin, short matchType, object userState) {
            if ((this.GetUCRDetailToLinkOperationCompleted == null)) {
                this.GetUCRDetailToLinkOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetUCRDetailToLinkOperationCompleted);
            }
            this.InvokeAsync("GetUCRDetailToLink", new object[] {
                        crID,
                        vin,
                        matchType}, this.GetUCRDetailToLinkOperationCompleted, userState);
        }
        
        private void OnGetUCRDetailToLinkOperationCompleted(object arg) {
            if ((this.GetUCRDetailToLinkCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetUCRDetailToLinkCompleted(this, new GetUCRDetailToLinkCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("UserCredentialsValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://metaoption.com/VerifyURL", RequestNamespace="http://metaoption.com", ResponseNamespace="http://metaoption.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ServiceResponce VerifyURL(string url) {
            object[] results = this.Invoke("VerifyURL", new object[] {
                        url});
            return ((ServiceResponce)(results[0]));
        }
        
        /// <remarks/>
        public void VerifyURLAsync(string url) {
            this.VerifyURLAsync(url, null);
        }
        
        /// <remarks/>
        public void VerifyURLAsync(string url, object userState) {
            if ((this.VerifyURLOperationCompleted == null)) {
                this.VerifyURLOperationCompleted = new System.Threading.SendOrPostCallback(this.OnVerifyURLOperationCompleted);
            }
            this.InvokeAsync("VerifyURL", new object[] {
                        url}, this.VerifyURLOperationCompleted, userState);
        }
        
        private void OnVerifyURLOperationCompleted(object arg) {
            if ((this.VerifyURLCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.VerifyURLCompleted(this, new VerifyURLCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://metaoption.com")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://metaoption.com", IsNullable=false)]
    public partial class UserCredentials : System.Web.Services.Protocols.SoapHeader {
        
        private string dealerCodeField;
        
        private string securityCodeField;
        
        private string legacySystemCodeField;
        
        private string iPAddressField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        public string DealerCode {
            get {
                return this.dealerCodeField;
            }
            set {
                this.dealerCodeField = value;
            }
        }
        
        /// <remarks/>
        public string SecurityCode {
            get {
                return this.securityCodeField;
            }
            set {
                this.securityCodeField = value;
            }
        }
        
        /// <remarks/>
        public string LegacySystemCode {
            get {
                return this.legacySystemCodeField;
            }
            set {
                this.legacySystemCodeField = value;
            }
        }
        
        /// <remarks/>
        public string IPAddress {
            get {
                return this.iPAddressField;
            }
            set {
                this.iPAddressField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://metaoption.com")]
    public partial class WebService_LinkCRResult {
        
        private int crField;
        
        private string vINField;
        
        private System.Nullable<short> yearField;
        
        private string makeField;
        
        private string modelField;
        
        private string bodyField;
        
        private int statusField;
        
        private System.DateTime cRDateField;
        
        private string datePublishedField;
        
        private string uRLField;
        
        /// <remarks/>
        public int CR {
            get {
                return this.crField;
            }
            set {
                this.crField = value;
            }
        }
        
        /// <remarks/>
        public string VIN {
            get {
                return this.vINField;
            }
            set {
                this.vINField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<short> Year {
            get {
                return this.yearField;
            }
            set {
                this.yearField = value;
            }
        }
        
        /// <remarks/>
        public string Make {
            get {
                return this.makeField;
            }
            set {
                this.makeField = value;
            }
        }
        
        /// <remarks/>
        public string Model {
            get {
                return this.modelField;
            }
            set {
                this.modelField = value;
            }
        }
        
        /// <remarks/>
        public string Body {
            get {
                return this.bodyField;
            }
            set {
                this.bodyField = value;
            }
        }
        
        /// <remarks/>
        public int Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime CRDate {
            get {
                return this.cRDateField;
            }
            set {
                this.cRDateField = value;
            }
        }
        
        /// <remarks/>
        public string DatePublished {
            get {
                return this.datePublishedField;
            }
            set {
                this.datePublishedField = value;
            }
        }
        
        /// <remarks/>
        public string URL {
            get {
                return this.uRLField;
            }
            set {
                this.uRLField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://metaoption.com")]
    public partial class ServiceResponce {
        
        private bool successField;
        
        private string messageField;
        
        private int cRNumberField;
        
        private string uRLField;
        
        private WebService_LinkCRResult[] recordsField;
        
        /// <remarks/>
        public bool Success {
            get {
                return this.successField;
            }
            set {
                this.successField = value;
            }
        }
        
        /// <remarks/>
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
        
        /// <remarks/>
        public int CRNumber {
            get {
                return this.cRNumberField;
            }
            set {
                this.cRNumberField = value;
            }
        }
        
        /// <remarks/>
        public string URL {
            get {
                return this.uRLField;
            }
            set {
                this.uRLField = value;
            }
        }
        
        /// <remarks/>
        public WebService_LinkCRResult[] Records {
            get {
                return this.recordsField;
            }
            set {
                this.recordsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetUCRDetailToLinkCompletedEventHandler(object sender, GetUCRDetailToLinkCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetUCRDetailToLinkCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetUCRDetailToLinkCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ServiceResponce Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ServiceResponce)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void VerifyURLCompletedEventHandler(object sender, VerifyURLCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class VerifyURLCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal VerifyURLCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ServiceResponce Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ServiceResponce)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591